apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-system
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 3000
      targetPort: app
    - name: app-debug
      port: 3010
      targetPort: app-debug
