apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: app
          resources:
            requests:
              cpu: "250m"
              memory: "36Mi"
            limits:
              cpu: "250m"
              memory: "36Mi"
