apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-system
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 8080
      targetPort: app
    - name: app-debug
      port: 6060
      targetPort: app-debug
