apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-system
data:
  READ_TIMEOUT: "5s"
  WRITE_TIMEOUT: "10s"
  IDLE_TIMEOUT: "120s"
  SHUTDOWN_TIMEOUT: "5s"
  API_HOST: "0.0.0.0:8080"
  DEBUG_HOST: "0.0.0.0:6060"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_LOG_LEVEL: "debug"
