apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.0
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: data
              mountPath: /data
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      wal:
        enabled: true
        dir: /data/wal
      chunk_idle_period: 3m
      max_chunk_age: 1h
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: inmemory

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/boltdb-cache
      filesystem:
        directory: /data/loki/chunks

    schema_config:
      configs:
        - from: "2025-05-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

    limits_config:
      retention_period: 168h
      max_streams_per_user: 5000
      allow_structured_metadata: false

    compactor:
      working_directory: /data/compactor
      retention_enabled: true
      delete_request_store: filesystem
