
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: observability
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observability
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
        volumeMounts:
        - name: pod-logs
          mountPath: /var/log/pods
          readOnly: true
        - name: promtail-config
          mountPath: /etc/promtail
      volumes:
      - name: pod-logs
        hostPath:
          path: /var/log/pods
      - name: promtail-config
        configMap:
          name: promtail-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      log_level: debug
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
        batchwait: 1s
        batchsize: 1024
    scrape_configs:
      # Direct file scraping job
      - job_name: direct-pod-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: app-logs
            __path__: /var/log/pods/app-system_app-*/*/*.log
        pipeline_stages:
          - cri: {}

      # Standard Kubernetes discovery job
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - cri: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node_name
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - action: replace
            replacement: /var/log/pods/${1}/${2}/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
