apiVersion: v1
kind: Namespace
metadata:
  name: app-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-system
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: app
          image: app-image
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 8080
            - name: app-debug
              containerPort: 6060
          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-system
spec:
  selector:
    app: app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-system
