apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: jaeger
        image: jaegertracing/opentelemetry-all-in-one:latest
        ports:
          - name: jaeger-ui
            containerPort: 16686
          - name: jaeger-grpc
            containerPort: 4317
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: app-system
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - name: jaeger-ui
    port: 16686
    targetPort: jaeger-ui
  - name: jaeger-grpc
    port: 4317
    targetPort: jaeger-grpc
