apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: app-system
data:
  prometheus.yml: |
    storage:
      tsdb:
        out_of_order_time_window: 30m
    otlp:
      promote_resource_attributes:
        - service.instance.id
        - service.name
        - service.namespace
        - deployment.environment
        - k8s.namespace.name
        - k8s.pod.name
      keep_identifying_resource_attributes: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.listen-address=:9090"
          - "--web.enable-lifecycle"
          - "--web.enable-otlp-receiver"
          - "--web.console.libraries=/etc/prometheus/console_libraries"
          - "--web.console.templates=/etc/prometheus/consoles"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: app-system
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
